### ISSUE TITLE
TNT's dont set off chain reactions

### ISSUE THREAD

**Issue by sk1bba** [LunaPixelStudios/Better-MC#1943]
### Describe the Bug

Just tried stripmining in the nether with TNT's no matter how they are placed they will not set off chain reactions

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.21

### Modloader

Forge

### Modpack Version

v16

**Comment by chorbintime** [comment]
Were the TNTs placed within radius of eachother?

Have you modified the modpack at all?

**Comment by SHXRKIEgg** [comment]
Fixed in Latest

**Comment by sk1bba** [comment]
> Were the TNTs placed within radius of eachother?
> 
> Have you modified the modpack at all?

Sorry for the late reply, as I mentioned no matter how I placed them they would not set eachother off. I tried with 1-4 blocks of space inbetween and they would only delete the other surrounding tnt's, not set them off

no modifications to the modpack

**Comment by chorbintime** [comment]
update the modpack to the latest version to resolve the issue

**Comment by sk1bba** [comment]
> update the modpack to the latest version to resolve the issue

Just tried it again in 16.5, still not setting off chain reactions

Haven't tried on the overworld but in the nether at Y: -14, any TNT configuration/placement will not cause a chainreaction

I love stripmining for ancient debree this way so it's really a bummer :(
