### ISSUE TITLE
JsonParseException: Don't know hot to turn {"color":"white"} into a Component

### ISSUE THREAD

**Issue by zero149** [LunaPixelStudios/Better-MC#783]
### Describe the Bug

I believe in the game I had just used a waystone to teleport back to a village I had previously visited. The client crashed at that time and now it crashes every time I try to load. I receive this error message:
Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"color":"white"} into a Component

I found a similar issue and solution in this reddit post:
https://www.reddit.com/r/feedthebeast/comments/xpd6ir/need_help_with_a_internal_exception_preventing_my/

I did try reviewing my inventory with NBTExplorer, but it does not look like RelicEX is in Better MC.

### Reproduction Steps

1. Connect to remote server
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/115188749/194418855-fe1d39ce-bbd5-454e-8695-3f5dc47c1e75.png)

### Crash Report or Log

https://pastebin.com/8A531xYq

### Operating System

Client is on Win 10, server is on Debian 11.5

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC Fabric 1.19.2 v7.5

### Optifine

No

### Other Mods

No other mods.

**Comment by zero149** [comment]
The pastebin link above is for curseforge\minecraft\Instances\Better MC [FABRIC] 1.19.2 (1)\logs\latest.log

There is also a crash report (I believe it is the same issue but from a different timestamp) here:
https://pastebin.com/i0emEgDW

**Comment by xSHXRKIEx** [comment]
Temporary solution is to /kill the player or delete there player data

**Comment by Claw256** [comment]
Did you find a solution to this? I don't want to delete the player data, and the solution could possibly be an item issue

**Comment by Claw256** [comment]
> 

Hi @zero149 , I actually fixed my issue last night. I had to edit the playerdata off the player on the server. What I did was go to the world folder on the server, go to the player data folder, and download the corresponding player data file, who's ID shows up in the server logs when the player joins. I then used this website to edit the NBT data: https://irath96.github.io/webNBT/. I edited the "Pos" tag (Aka co-ordinates position) of the player to a different location, which was the X Y and Z coordinates of our spawn house. I then downloaded said .dat file I was editing, replaced it in the world playerdata folder on the server, and the issue was fixed :)

**Comment by zero149** [comment]
@Claw256 Oh, nice. I was debating editing the player coords, but we spun up a different server before I could get someone to verify the coords of where I wanted to move the player to.

Glad to hear you got this resolved!

**Comment by dylanharty** [comment]
@Claw256 Thank you. This was life saving information. We got the same error upon dying in a new biome and could not log back on to our server. 

@xSHXRKIEx We updated our server from Medieval MC [FABRIC] 1.19.2 v7 -> Medieval MC [FABRIC] 1.19.2 v8.5 a couple days ago and and got this error today. We have noticed a few text things broken showing the moon rising messages now can just be the string variable name. Anyways my question is, is it not recommended to update to newer modpacks of the same? If not is there anyway to update the server without losing data but also having the updates? Furthermore do you recommend to roll back to v7?

**Comment by kjmabj** [comment]
This issue persists. Installed server yesterday, version 9 (Oct. 22.). Same error message as in original post.

**Comment by usa1ph** [comment]
> > 
> 
> Hi @zero149 , I actually fixed my issue last night. I had to edit the playerdata off the player on the server. What I did was go to the world folder on the server, go to the player data folder, and download the corresponding player data file, who's ID shows up in the server logs when the player joins. I then used this website to edit the NBT data: https://irath96.github.io/webNBT/. I edited the "Pos" tag (Aka co-ordinates position) of the player to a different location, which was the X Y and Z coordinates of our spawn house. I then downloaded said .dat file I was editing, replaced it in the world playerdata folder on the server, and the issue was fixed :)

I can't seem to find the Pos in the editor.

**Comment by Volodesi** [comment]
I had this happen tonight. Editing my coordinates back to spawn fixed it.

Was on Fabric V13 HF

**Comment by TheGag96** [comment]
Happened on my server also - unsure if it will come back if someone goes back to the location it was triggering in.

**Comment by GGabi** [comment]
@xSHXRKIEx 
This issue should not be marked as completed because the problem still persists, no action was taken and it appears not to be a result of updating the modpack version from glancing at the feedback given above.
This has happened to multiple players on my server, specifically after using waypoints.

**Comment by Cboyatcboy** [comment]
I'm having same issue, and Claw256's work around did end up working, though i have to change the .dat and .dat_old a decent distance (i did 0,80,0)

**Comment by MrG-DRGN** [comment]
Same issue still exists. Can't get into my server.

**Comment by davidrochin** [comment]
Is this ever being properly fixed? It basically makes it so I can't go to any of the villages I discover after a while.

**Comment by WaveringAna** [comment]
it looks like they have no interest in fixing the bug lol
https://github.com/LunaPixelStudios/Better-MC/issues/814

**Comment by WaveringAna** [comment]
![image](https://user-images.githubusercontent.com/10069649/210434017-451f31cf-f272-42ff-b17e-8580f61720fd.png)
don't expect this to get fixed

**Comment by GGabi** [comment]
Embarrassing, at least put some effort into either diagnosing what's actually going wrong, or communicating what they know more clearly so we can find our own fixes beyond /kill.

**Comment by TheSeems** [comment]
If someone is still struggling to solve this issue, i've coded myself a one-time fix. Seems like it works for me, so im sharing.

**Note**: i am not a mod developer, this mod is not for the production.

https://github.com/TheSeems/PacketPray/releases

**Comment by chorbintime** [comment]
> @xSHXRKIEx This issue should not be marked as completed because the problem still persists, no action was taken and it appears not to be a result of updating the modpack version from glancing at the feedback given above. This has happened to multiple players on my server, specifically after using waypoints.

> Is this ever being properly fixed? It basically makes it so I can't go to any of the villages I discover after a while.

> it looks like they have no interest in fixing the bug lol #814

> ![image](https://user-images.githubusercontent.com/10069649/210434017-451f31cf-f272-42ff-b17e-8580f61720fd.png) don't expect this to get fixed

> Embarrassing, at least put some effort into either diagnosing what's actually going wrong, or communicating what they know more clearly so we can find our own fixes beyond /kill.

Hello, 

I would like to apologize on behalf of our studio for this issue going unnoticed. When this was originally posted, I had just started managing the GitHub, as Sharkie has been on hiatus since around late October. 

Because the issue was marked as complete, and I never responded to the issue, I was completely unaware of this issue's existence. Sharkie has not been active on GitHub since I took control, so he also was not aware that there were new comments.

There are a few things which I feel are necessary to acknowledge before we continue:

1) Both me and Sharkie, the only developers working on all 16 of our modpacks, have repeatedly tried to recreate the issue with no success.
2) Every instance of reproduction steps varies, and there is no concrete reason I have found for it happening. People have said it's something to do with waystones - but people with no waystones at all experience it. People claim it's due to pillagers, but some have experienced it with no pillagers nearby. Other people have claimed it's a minimap issue, but it happens across two modpacks which use different minimap mods.
3) I have repeatedly tried to work with people actively experiencing the issue to troubleshoot the reason for this happening, but I have never gotten a response back. I can supply screenshots of this, if necessary. 
I trust that, if I was aware of this thread, I could have troubleshooted this with you folks. 
4) The issues from October were originally closed because we were going to try and find a permanent solution after finishing the next modpack update, which was planned in the next few days, as it could've been fixed in one of the mod updates. Because we couldn't recreate the issue, I started troubleshooting the issue with other people whenever I wasn't busy, but none of these people were willing to help me find a permanent fix. They would instead take one of temporary solutions and then not get back to me. 




> If someone is still struggling to solve this issue, i've coded myself a one-time fix. Seems like it works for me, so im sharing.
> 
> **Note**: i am not a mod developer, this mod is not for the production.
> 
> https://github.com/TheSeems/PacketPray/releases

This is the message which made me aware of this thread. Seems dm'ed me on Discord today, and from this point I will be suggesting those who experience this issue to try adding PacketPray. I will update the FAQ in our Discord accordingly. 

Thank you for your patience.

**Comment by GGabi** [comment]
Thank you for taking the time to get back to us, it's good to know that this is on the radar.
I completely understand the frustration of not being able to recreate the issue reliably, if it happens again I'll do my best to debug and get back to you.

**Comment by CriNotCree** [comment]
@chorbintime I just experienced this issue on the Medieval MC [Fabric] 1.19.2 pack. I haven't used the PacketPray fix yet to see if it works, but to help diagnose the issue I figured I'd give insight into the order of events that led up to the bug in my situation.

- I boarded a pirate ship. 
- I picked up a pillager banner of some kind. 
- A pillager raid bar appeared ,and many started spawning. 
- I died to them, then returned and swam to the ship.
- I boarded the ship once more.
- I opened the grave, and immediately received the error. 

Every subsequent attempt to join resulted in the same error.

**Comment by chorbintime** [comment]
> @chorbintime I just experienced this issue on the Medieval MC [Fabric] 1.19.2 pack. I haven't used the PacketPray fix yet to see if it works, but to help diagnose the issue I figured I'd give insight into the order of events that led up to the bug in my situation.
> 
> * I boarded a pirate ship.
> * I picked up a pillager banner of some kind.
> * A pillager raid bar appeared ,and many started spawning.
> * I died to them, then returned and swam to the ship.
> * I boarded the ship once more.
> * I opened the grave, and immediately received the error.
> 
> Every subsequent attempt to join resulted in the same error.

Did PacketPray fix it?

**Comment by Croissantt18** [comment]
I'm having this issue after using a waypoint to teleport to a village that a raid was started at. I can no longer get into the server and are currently trying to install PacketPray. Problem is I have no idea on how to do so, I downloaded the files but kinda need help. I am the server owner and just cannot figure out what to add where.

Any help will be greatly appreciated.

**Comment by WaveringAna** [comment]
> I'm having this issue after using a waypoint to teleport to a village that a raid was started at. I can no longer get into the server and are currently trying to install PacketPray. Problem is I have no idea on how to do so, I downloaded the files but kinda need help. I am the server owner and just cannot figure out what to add where.
> 
> Any help will be greatly appreciated.

drop the jar into the mods folder on your server




> > @chorbintime I just experienced this issue on the Medieval MC [Fabric] 1.19.2 pack. I haven't used the PacketPray fix yet to see if it works, but to help diagnose the issue I figured I'd give insight into the order of events that led up to the bug in my situation.
> > 
> > * I boarded a pirate ship.
> > * I picked up a pillager banner of some kind.
> > * A pillager raid bar appeared ,and many started spawning.
> > * I died to them, then returned and swam to the ship.
> > * I boarded the ship once more.
> > * I opened the grave, and immediately received the error.
> > 
> > Every subsequent attempt to join resulted in the same error.
> 
> Did PacketPray fix it?

packetpray seems to have fixed it for me; I think it might be entity related because when a friend ran into it they were in a cave under an occurring raid. I tp'd them out but when I went into it in spec view I was crashing as well. After some time and the raid cleared, I went there again and I was never able to reproduce the crashing

**Comment by CriNotCree** [comment]
> Did PacketPray fix it?
@chorbintime It did, I dropped it in both the server mods folder as well as on my client's mod folder. Afterwards I tested to see if dying and opening my grave caused an issue again, which it didn't. I defeated the raid, removed the jar from my client's mod folder and waited for another raid to occur. 

I died in a different village this time, opened my grave and crashed again, experiencing the same issue. Re-adding the jar to my mods folder instantly remedied the issue for me and I was able to login again. It seems from my testing that it has to do with pillager raids and picking up graves near them, possibly picking up an inventory with a banner or other pillager items in it? That's my best guess. Both times I could not find any immediate way stones in my vicinity, so in this instance that causes the bug, I don't believe it is related to that. Hope this helps, let me know if there's anything else I can do to test for.

**Comment by VVNELLE** [comment]
Ran into the same problem yesterday on Better Minecraft. Had to have my coordinates changed by the admin in order to log back into the server. Basically we had built a raid farm and I voluntarily DCed so that my friends could sleep through the night. I had DC'd in the middle of a raid and when I tried to log back into the game that's when I got the error and couldn't log in.

Once I had my coords changed I could log back normally. All waypoints were fine except when I tried to waypoint back to the raid farm I immediately got the same error message. I manually ran back to the raid farm and realized I was still in the middle of a raid. Once I completed the raid I was able to use the waypoint with no issues.

**Comment by chorbintime** [comment]
Add the PacketPray mod on clientside & serverside to fix the issue permanently. https://www.curseforge.com/minecraft/mc-mods/packetpray

**Comment by TechnoIsHere** [comment]
@chorbintime I just got the error today but luckily this thread helped me to fix it. 

- In my case, teleporting, respawning OR relogging, in the area with a raid caused the error to occur.
- Flying or walking into the raid area did not cause the error to occur.
- Our area that was affected had a bunch of create machines, decor blocks, and monster spawners due to a mob farm.
- This is a server hosted by Apex Hosting
- Modpack is BIgChadGuys Plus w/ Cobblemon 2.11.0, MC version 1.21.1
 
 imo waystones are just an easy way to TP so it should not be considered. I'm thinking it has to do something with the client and raids, a specific mod, or a specific entity (most likely villagers if anything, could be cats, iron golems etc..) in combination with the raids, something that shares a connection with all the other people that it had to happen to so far
 
 id be willing to help out if u still want to investigate it, I could share the world link and recreate the events as well.

**Comment by OskarTwarowski** [comment]
hey i know its 2025, i got same bug right after teleporting to my friends base ( he got this bug too) and after fixing it with packet pray i logged on, i have raid incidator on top ( we have villagers) so i think its connected

**Comment by JohnRamberger** [comment]
We had this occur, Player was in a pillager lookout and not a village. Might be due to pillagers.

**Comment by jaydee0004** [comment]
Hi all just want to say I had this as well in our server. The raid happened and my friend got disconnected. All possible culprits are I think that relates to raids is Illager Invasion. Besides that, I'm not sure.

**Comment by yippeeeyay** [comment]
Just had this happen on BigChadGuys Plus w/Cobblemon on 1.20.1. I deleted my player data which fixed it at first but then I tried teleporting to where I was before. There was a raid happening and I got the error again. I fixed this by deleting the mod VIllager Names

**Comment by WheelerShigley** [comment]
I also just had this happen on BigChadGuys Plus w/Cobblemon on 1.20.1; removing  VIllager Names and Illager Invasion did solve it.
I suspect it may be from my client using a newer version of Java (24, in my case), compared to what 1.20.1 was mainly on (21, I believe).
